eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: FEIGN-TRADING-BACKTEST-VIEW
  thymeleaf:
    mode: LEGACYHTML5
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html

#链路追踪地址
zipkin:
  base-url: http://localhost:9411